- name: Run pre_deploy hooks
  vars:
    hooks: "{{ pre_deploy | default([]) }}"
    step: pre_deploy
  ansible.builtin.import_playbook: ./hooks.yml

- name: Prepare EDPM baremetal playbook
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Load parameters files
      ansible.builtin.include_vars:
        dir: "{{ cifmw_basedir }}/artifacts/parameters"

    - name: Deploy podified control plane
      ansible.builtin.import_role:
        name: edpm_prepare

    - name: Perform Podified and EDPM deployment on compute nodes with virtual baremetal
      when: cifmw_edpm_deploy_baremetal | default('false') | bool
      ansible.builtin.import_role:
        name: edpm_deploy_baremetal

- name: Run post_ctlplane_deploy hooks
  when: not cifmw_edpm_deploy_baremetal | default('false') | bool
  vars:
    hooks: "{{ post_ctlplane_deploy | default([]) }}"
    step: post_ctlplane_deploy
  ansible.builtin.import_playbook: ./hooks.yml

- name: EDPM deployment on pre-provisioned VMs
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Load parameters files
      ansible.builtin.include_vars:
        dir: "{{ cifmw_basedir }}/artifacts/parameters"

    - name: Create VMs and Deploy EDPM
      when:
        - not cifmw_edpm_deploy_baremetal | default('false') | bool
        - cifmw_deploy_edpm | default('false') | bool
      block:
        - name: Create and provision external computes
          when:
            - cifmw_use_libvirt is defined
            - cifmw_use_libvirt | bool
          ansible.builtin.import_role:
            name: libvirt_manager
            tasks_from: deploy_edpm_compute.yml

        - name: Disable discover_hosts when deploying HCI phase1
          when: cifmw_edpm_deploy_hci | default(false) | bool
          ansible.builtin.set_fact:
            cifmw_edpm_deploy_skip_nova_discover_hosts: true

        - name: Deploy EDPM
          ansible.builtin.import_role:
            name: edpm_deploy

- name: Deploy ceph deploy playbook
  ansible.builtin.import_playbook: ceph.yml
  when: cifmw_edpm_deploy_hci | default(false) | bool

- name: Deploy remaining services when HCI environment
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Create Ceph secrets and retrieve FSID info
      when: cifmw_edpm_deploy_hci | default(false) | bool
      block:
        - name: Create Ceph secrets and retrieve FSID info
          environment:
            PATH: "{{ cifmw_path }}"
            KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
          block:
            - name: Set ceph secret path
              ansible.builtin.set_fact:
                ceph_secret_path: "/tmp/k8s_ceph_secret.yml"

            - name: Create ceph config secret
              ansible.builtin.command: >-
                oc apply -f {{ ceph_secret_path }}
              register: apply_result
              changed_when: ('stdout' in apply_result) and ('unchanged' not in apply_result.stdout)
              failed_when: ( apply_result.rc | int ) > 0

            - name: Set Ceph FSID fact
              ansible.builtin.set_fact:
                cifmw_edpm_deploy_ceph_fsid: "{{ (lookup('template', ceph_secret_path)|from_yaml).data['ceph.conf'] \
                | b64decode | regex_search('fsid = (.*)', '\\1')}}"

        - name: Copy kustomizations from phase2 to dataplane dir
          ansible.builtin.copy:
            src: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/hciphase2/"
            dest: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/dataplane/"
            remote_src: yes

        - name: Enabled nova discover_hosts after deployment
          ansible.builtin.set_fact:
            cifmw_edpm_deploy_skip_nova_discover_hosts: false

        - name: Continue HCI deployment
          ansible.builtin.import_role:
            name: edpm_deploy

- name: Run post_deploy hooks
  vars:
    hooks: "{{ post_deploy | default([]) }}"
    step: post_deploy
  ansible.builtin.import_playbook: ./hooks.yml
