- name: Run pre_deploy hooks
  vars:
    hooks: "{{ pre_deploy | default([]) }}"
    step: pre_deploy
  ansible.builtin.import_playbook: ./hooks.yml

- name: Prepare EDPM baremetal playbook
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Load parameters files
      ansible.builtin.include_vars:
        dir: "{{ cifmw_basedir }}/artifacts/parameters"

    - name: Deploy podified control plane
      ansible.builtin.import_role:
        name: edpm_prepare

    - name: Perform Podified and EDPM deployment on compute nodes with virtual baremetal
      when: cifmw_edpm_deploy_baremetal | default('false') | bool
      ansible.builtin.import_role:
        name: edpm_deploy_baremetal

- name: Run post_ctlplane_deploy hooks
  when: not cifmw_edpm_deploy_baremetal | default('false') | bool
  vars:
    hooks: "{{ post_ctlplane_deploy | default([]) }}"
    step: post_ctlplane_deploy
  ansible.builtin.import_playbook: ./hooks.yml

- name: EDPM deployment on pre-provisioned VMs
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Load parameters files
      ansible.builtin.include_vars:
        dir: "{{ cifmw_basedir }}/artifacts/parameters"

    - name: Create VMs and Deploy EDPM
      when:
        - not cifmw_edpm_deploy_baremetal | default('false') | bool
        - cifmw_deploy_edpm | default('false') | bool
      block:
      - name: Create and provision external computes
        when:
          - cifmw_use_libvirt is defined
          - cifmw_use_libvirt | bool
        ansible.builtin.import_role:
          name: libvirt_manager
          tasks_from: deploy_edpm_compute.yml

      - name: Enabled only network services for HCI deploy
        when:
          - cifmw_edpm_deploy_hci | default(false) | bool
        ansible.builtin.set_fact:
          cifmw_edpm_deploy_network_only: true
          cifmw_edpm_deploy_storage_mgmt_network: true
          cifmw_edpm_deploy_enable_hci_nova_config: false

      - name: Deploy EDPM
        ansible.builtin.import_role:
          name: edpm_deploy

- name: Deploy ceph deploy playbook
  ansible.builtin.import_playbook: ceph.yml
  when: cifmw_edpm_deploy_hci | default(false) | bool

- name: Deploy remaining services in HCI environment
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Create Ceph secrets and retrieve FSID info
      when: cifmw_edpm_deploy_hci | default(false) | bool
      block:
        - name: Update deploy configuration
          ansible.builtin.set_fact:
            cifmw_edpm_deploy_network_only: false
            cifmw_edpm_deploy_storage_mgmt_network: true
            cifmw_edpm_deploy_enable_hci_nova_config: true
            cifmw_edpm_deploy_ceph_fsid: "{{ cifmw_ceph_fsid }}"

        - name: Continue HCI deployment
          ansible.builtin.import_role:
            name: edpm_deploy

- name: Run post_deploy hooks
  vars:
    hooks: "{{ post_deploy | default([]) }}"
    step: post_deploy
  ansible.builtin.import_playbook: ./hooks.yml
